3-module: 1-5 tasks
js-tasks-ru/jsbasic-20230629_nadya-karandasheva pull request #4
Opened 2023-07-14 20:34 UTC by Nadya-Karandasheva

2023-07-14 20:35 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-07-17 10:16 UTC, SinimaWath requested changes

2023-07-17 10:16 UTC, SinimaWath commented on 3-module/4-task/index.js
> +  });
Этот forEach, стоит заменить на: `.join('\n')`

2023-07-17 18:08 UTC, nadyakarandasheva commented on 3-module/4-task/index.js
> +  });
исправила

2023-07-17 18:09 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-07-22 19:20 UTC, SinimaWath approved these changes

2023-07-22 19:20 UTC, SinimaWath commented on 3-module/3-task/index.js
> +  return result.join('');
Задачу можно упростить до:

```
str.split('-').map((value, index) => ....).join('')
```

2023-07-22 19:21 UTC, merged